version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  assignees:
  - folfy
